apiVersion: v1
kind: Service
metadata:
  name: ferapp
  labels:
    app: ferapp
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30009
      targetPort: 8000  # Replace with the port your app runs on inside the pod
  selector:
    app: ferapp
    tier: frontend
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ferapp-pv
  labels:
    app: ferapp
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  # Matches the PVC storage class
  hostPath:  # Replace with your desired storage solution
    path: /mnt/data  # Ensure this path exists on your host machine
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ferapp-pv-claim
  labels:
    app: ferapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual  # Matches the PV storage class
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ferapp
  labels:
    app: ferapp
spec:
  replicas: 1 # Specify the number of replicas for the deployment
  selector:
    matchLabels:
      app: ferapp
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ferapp
        tier: frontend
    spec:
      containers:
        - name: ferapp
          image: hosamzolfonoon/ferportal:latest
          command: ["nginx", "-g", "daemon off;"] # Keeps Nginx running in the foreground
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: ferapp-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: ferapp-persistent-storage
          persistentVolumeClaim:
            claimName: ferapp-pv-claim
